# version: "3.9"

# the services part
services:
#mariadb
  mariadb:
    image: mariadb:fvan-wij
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - mariadb:/var/lib/mysql
    env_file :
      - .env
    networks :
      - inception
    restart: always
#nginx
  nginx:
    image: nginx:fvan-wij
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    restart: always
#wordpress
  wordpress:
    image: wordpress:fvan-wij
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/wordpress
    env_file :
      - .env
    networks:
      - inception
    restart: always

# the volumes part
volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/fvan-wij/data/mariadb
      o : bind
      type : none
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/fvan-wij/data/wordpress
      o : bind
      type : none

# the networks part
networks:
  inception:
    name: inception
